### ISSUE TITLE
README.md has incorrect information about dependency

### ISSUE THREAD

**Issue by eashwaranp** [nats-io/nats-java-vertx-client#49]
The https://github.com/nats-io/nats-java-vertx-client/blob/main/README.md#using-the-vertx-nats-client section talks about nats-vertx-nats-interface, but I can't find this package anywhere.  

Googling for this brings up https://central.sonatype.com/artifact/io.nats/nats-vertx-interface/1.3.0-beta15, which is nats-vertx-interface, different from nats-vertx-nats-interface.  

I got the nats-vertx-interface from the sonatype site, since it had Synadia as a contributor.  If this is the right one, then please update the README.md accordingly.

Thanks.

**Comment by RichardHightower** [comment]
fixed. in next release.
