### ISSUE TITLE
Vertx NATSClient should support custom Vertx messages (feature request, need more specifications)

### ISSUE THREAD

**Issue by marthaCP** [nats-io/nats-java-vertx-client#6]
NatsClient subscribe Interface doesn't support custom vertex message. Right now its supporting generic message interface which can lead to runtime issues.

**Comment by RichardHightower** [comment]
Can I get some more examples of this? I am not sure I 100% understand the ask.

**Comment by RichardHightower** [comment]
Are we talking about 

https://github.com/vert-x3/vertx-examples/blob/4.x/core-examples/src/main/java/io/vertx/example/core/eventbus/messagecodec/util/CustomMessageCodec.java

I don't remember this as an ask in the original meetings. But I can look into adding it.
