### ISSUE TITLE
executeBlocking method

### ISSUE THREAD

**Issue by marthaCP** [nats-io/nats-java-vertx-client#7]
when calling the executeBlocking method, the version that only takes a handler

**Comment by marthaCP** [comment]
There is an extended version that also takes additional arguments. One of which is called ordered. That controls if the executions for that context will be executed serially or in parallel, if executeBlocking is called several times on the same context. If true calls are serialized, while if false then they will be no ordering guarantees. The default value is true. So, the Vertx client uses true, which means only one message per context is sent at a time, which will affect throughput.

**Comment by RichardHightower** [comment]
This seems like an easy fix and low-hanging fruit.
