### ISSUE TITLE
Question on NATS Java client tooling

### ISSUE THREAD

**Issue by marthaCP** [nats-io/nats-java-vertx-client#9]
There is a tool in NATS which provides testing the specifics to the NATS Java client called Jetstream Multi tool - https://github.com/nats-io/java-nats-examples/tree/main/js-multi-tool. 

Can this be used for testing vert.x?

**Comment by RichardHightower** [comment]
Scott mentioned that it could be used. I will circle back with Scott and check.

**Comment by RichardHightower** [comment]
Need more info
